### ISSUE TITLE
Some punctuation characters missing

### ISSUE THREAD

**Issue by hernandezrivera** [davidmogar/cucco#48]
Thanks for This amazing library!

It seems that replace_punctuation is missing these 2 characters: ” “

**Comment by davidmogar** [comment]
Hi @hernandezrivera 

Cucco only removes punctuation characters as those defined in `string.punctuation`. An example of quotes removal would be the next one:

```
>>> from cucco import Cucco
>>> cucco = Cucco()
>>> print(cucco.normalize('Who let the "cucco" out?', ['replace_punctuation']))
Who let the cucco out
```

In the case of wanting to remove "special" characters, you will have to use [replace_characters](https://github.com/davidmogar/cucco/blob/master/cucco/cucco.py#L202) function.

Cheers!
